name: tres_astronautas
version: 1.0.0+1
publish_to: none
description: Flutter prueba tecnica
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_login: ^4.0.0
  flutter_svg: ^1.1.3
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_slidable: ^2.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  test: ^1.21.4

flutter: 
  uses-material-design: true

  assets:
    - assets/